### ISSUE TITLE
PRD.util.coerceToString should return default value on empty strings and arrays

### ISSUE THREAD

**Issue by fernandofreitasdh** [fchierad/PRD#10]
v1.0.3 - proposed changed code:

  function coerceToString( input, defVal ) {
    var ret = ''**, str**;
    /* Throughout this function String() is used to guarantee that the string generated
     * is an ECMA string. This is only a concern on the workflow engine since the engine
     * allows a mix of ECMA and Java code. Returning a Java string will cause the
     * toJSON() function to fail when using JSON.stringify(), hence this safety.
     */
    if ( defVal != null && typeof defVal === 'string' ) {
      ret = String( defVal );
    }
    if ( input === null || input === undefined ) {
      return ret;
    }
    if ( typeof input === 'string' || typeof input === 'number' || typeof input === 'boolean' ) {
      **str** = String( input );
    }
    if ( input instanceof Array ) {
      **str** = String( input.join( ' ' ) );
    }
    **if ( str !== '' ) {
      ret = str;
    }**
    return ret;
  }

**Comment by fchierad** [comment]
Added proposed code to branch 1.0.4wip .
