### ISSUE TITLE
PRD.IDVglobalQuery Not working as expected

### ISSUE THREAD

**Issue by bshefflette** [fchierad/PRD#13]

**Comment by fchierad** [comment]
Let me know more details/duplication steps if it happens again. the IDVglobalQuery tests were performed all on the engine side so it would be interesting to know if the issue happened when using it on the engine or a form.

**Comment by bshefflette** [comment]
It was my mistake, my PRD.init() function was calling the api objects in
the wrong order, I had them as IDVault, Form, Field lol.
