### ISSUE TITLE
PRD.init()

### ISSUE THREAD

**Issue by bshefflette** [fchierad/PRD#14]
could you add a feature to detect what parameters i'm inputting wrong on this function? it took me a while to figure out that i was putting these objects in the wrong order.

**Comment by fchierad** [comment]
will check the objects by type and content. A quick peek on a form shows this:

Object.keys( IDVault );

["globalQuery", "containers", "get", "globalList", "getGuidFromDn", "getDnFromGuid", "execService"]

Object.keys( form );

["getField", "alert", "showMsg", "showWarning", "showError", "showFatal", "validate", "submit", "getLabel", "hide", "show", "enable", "disable", "getValue", "getValues", "getAllValues", "setValues", "focus", "select", "activate", "setRequired", "interceptAction", "getLocale", "getDefaultLocale", "getRBMessage", "stringToDate", "dateToString", "isValidDate", "showDebugMsg", "addCustomValidation", "clearMessages"]

Object.keys( field );

["getName", "getLabel", "validate", "fireEvent", "hide", "show", "enable", "disable", "getValue", "getValues", "getAllValues", "setValues", "focus", "select", "activate", "setRequired"]

**Comment by fchierad** [comment]
code complete, basic testing performed with IDM 4.5. Closing issue.
https://github.com/fchierad/PRD/blob/1.0.4wip/PRD.md#PRD.init
