### ISSUE TITLE
Support for auto-setValues to form for get and globalQuery

### ISSUE THREAD

**Issue by bshefflette** [fchierad/PRD#15]
Can you add support for these functions to auto-setValues to form fields: IDVault.get & IDVault.globalQuery?

**Comment by fchierad** [comment]
Will do, will try and make the parameters variable like in the original function while keeping the remainder of the functionality intact. Do you want to mirror the form version and place that as the first parameter or can it be the last parameter?

**Comment by fchierad** [comment]
changes made and validated.
