### ISSUE TITLE
Dedup & Diff

### ISSUE THREAD

**Issue by bshefflette** [fchierad/PRD#2]
Could you add an optimized array dedup and array diff w/ optionial param for ignored or exact case.

**Comment by fchierad** [comment]
Just to confirm since most RBPM back-end pieces uses arrays and Vectors with one level and strings, would it be OK for the initial release of the requested functionality to focus on 1 level array/Vector of strings?

**Comment by bshefflette** [comment]
Yes that'd be great, thank you!

**Comment by fchierad** [comment]
Deduplication is code complete and tested/validated, will be PRD.util.Unique(). 

Diff will be PRD.util.Compare and development is in progress. Initial plan is to return an array of arrays where the return will be [ [elements only in first parameter], [elements only in second parameter], [elements in both] ].

Given how everything we retrieve from flowdata in RBPM are text nodes this first iteration coerces the input values to string and assumes uni-dimensional arrrays/vectors as inputs.

**Comment by fchierad** [comment]
testing completed.
