### ISSUE TITLE
Error on ctask

### ISSUE THREAD

**Issue by bshefflette** [fchierad/PRD#27]
Error: isString is undefined at time when partition_create is called.

Line 40->Line47
```
40 - PRD.extensions.ctask = partition_create( msgprefix, storage, mainpartitionname, 'basic' );
41 - initref = PRD.extensions.ctask;
42 - // Function abstractions for easier refactoring
43 - logmsg = PRD.util.logerror;
44 - dbgmsg = PRD.util.debugmsg;
45 - isString = PRD.util.isString;
46 - isNumber = PRD.util.isNumber;
47 - isBoolean = PRD.util.isBoolean;
```

Fixes:
ordering lines 40&41 to occur after line 47 `isBoolean = PRD.util.isBoolean`, 
**or** use `PRD.util.isString` in the partition_create function.

**Comment by fchierad** [comment]
thanks for the report, fix performed and pushed. Note to self: add mocha tests with PRD loaded as well :)
