### ISSUE TITLE
getObject to Ecma Array

### ISSUE THREAD

**Issue by bshefflette** [fchierad/PRD#3]
Can you add a function that takes flowdata.getObject('abc') as an input and adds all items from that flowdata into an ecma array *single level to start? (can this have empty flowdata elements return an empty ecma array ?)

**Comment by fchierad** [comment]
flowdata.getObject() returns an object of class org.apache.xerces.dom.ElementNSImpl. Might be easier to build a recursive iteration to convert all element nodes to properties and all text nodesets to arrays with individual nodes being elements on the array. That would give a consistent representation of the data given flowdata's DOM does not uses attribute nodes nor namespace properties as far as I could tell.

**Comment by fchierad** [comment]
so from the above a flowdata.getObject( 'someXpathhere' ) that return a dom structure represented by the xml:
&lt;test&gt;
&nbsp;&nbsp;&nbsp;&lt;val&gt;1&lt;/val&gt;
&nbsp;&nbsp;&nbsp;&lt;prop&gt;abc&lt;/prop&gt;
&nbsp;&nbsp;&nbsp;&lt;prop&gt;def&lt;/prop&gt;
&lt;/test&gt;

would be converted to the ECMA object:
{
&nbsp;&nbsp;&nbsp;test:
&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;val:[&nbsp;1&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;prop:[&nbsp;'abc',&nbsp;'def'&nbsp;]
&nbsp;&nbsp;&nbsp;}
}

**Comment by fchierad** [comment]
Found out you can have text and element nodes mixed at the same level in flowdata, just like in regular XML. Could not set XML attributes yet though. So the resulting structure would have to be something like this instead:

{
&nbsp;&nbsp;&nbsp;test:
&nbsp;&nbsp;&nbsp;[{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;val:[&nbsp;1&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;prop:[&nbsp;'abc',&nbsp;'def'&nbsp;]
&nbsp;&nbsp;&nbsp;}]
}

**Comment by fchierad** [comment]
First iteration works correctly with 1 level lists as requested, and with arbitrary depth lists where the element names do not repeat. Opened issue https://github.com/fchierad/PRD/issues/7 to continue working on that scenario for v1.0.3 so that v1.0.2 can be released.
